# Generated by Django 3.2 on 2024-05-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20240506_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('count', models.IntegerField(default=0, verbose_name='库存')),
            ],
        ),
        migrations.DeleteModel(
            name='MyDem',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='up_date',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工资'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ct_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=16, verbose_name='姓名'),
        ),
    ]
