# Generated by Django 3.2 on 2024-05-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20240507_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ct_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
